export const expansionFamilies=[
{id:'transition-shutter-slice',nameJa:'シャッター・スライス遷移',nameEn:'Shutter Slice Transition',category:'transition',categoryName:'Transitions',subcategory:'Slice & Wipe',description:'複数の縦スライスが時間差で閉じて次シーンを覆い、反対方向へ開いて遷移する。',purpose:'Page transition / Campaign / Portfolio',tech:['CSS clip-path / GSAP'],editable:['slice count','stagger','direction','easing'],difficulty:'Medium',load:'Light',priority:'A',previewType:'transition',variants:[{id:'transition-shutter-slice',nameJa:'シャッター・スライス遷移',nameEn:'Shutter Slice Transition'}]},
{id:'transition-iris-aperture',nameJa:'アイリス・アパーチャ遷移',nameEn:'Iris Aperture Transition',category:'transition',categoryName:'Transitions',subcategory:'Mask',description:'カメラ絞りのような多角形マスクが閉じて再び開き、シーンを切り替える。',purpose:'Film / Photography / Luxury',tech:['CSS clip-path / SVG mask'],editable:['blades','origin','duration','rotation'],difficulty:'Medium',load:'Light',priority:'A',previewType:'transition',variants:[{id:'transition-iris-aperture',nameJa:'アイリス・アパーチャ遷移',nameEn:'Iris Aperture Transition'}]},
{id:'transition-card-flip',nameJa:'3Dカード・フリップ遷移',nameEn:'3D Card Flip Transition',category:'transition',categoryName:'Transitions',subcategory:'3D',description:'現在シーンをカード面として3D回転し、裏面から次シーンを出現させる。',purpose:'Portfolio / Product / Story',tech:['CSS 3D / GSAP'],editable:['axis','perspective','shadow','duration'],difficulty:'Medium',load:'Light',priority:'A',previewType:'transition',variants:[{id:'transition-card-flip',nameJa:'3Dカード・フリップ遷移',nameEn:'3D Card Flip Transition'}]},
{id:'background-aurora-flow',nameJa:'オーロラ・フロー背景',nameEn:'Aurora Flow Background',category:'background',categoryName:'Background / Atmosphere',subcategory:'Gradient Field',description:'複数の発光グラデーションがゆっくり漂い、オーロラ状の奥行きと色変化を作る。',purpose:'Hero / Beauty / Tech / Luxury',tech:['CSS gradients / WebGL optional'],editable:['palette','speed','blur','blend'],difficulty:'Easy',load:'Light',priority:'A',previewType:'background',variants:[{id:'background-aurora-flow',nameJa:'オーロラ・フロー背景',nameEn:'Aurora Flow Background'}]},
{id:'background-grid-warp',nameJa:'グリッド・ワープ背景',nameEn:'Warped Grid Background',category:'background',categoryName:'Background / Atmosphere',subcategory:'Grid',description:'遠近グリッドが波打ちながら奥行き方向へ流れ、デジタル空間を演出する。',purpose:'Tech / Game / Digital',tech:['CSS 3D / Canvas'],editable:['grid size','depth','wave','speed'],difficulty:'Medium',load:'Medium',priority:'A',previewType:'background',variants:[{id:'background-grid-warp',nameJa:'グリッド・ワープ背景',nameEn:'Warped Grid Background'}]},
{id:'background-noise-cloud',nameJa:'ノイズ雲・ドリフト',nameEn:'Noise Cloud Drift',category:'background',categoryName:'Background / Atmosphere',subcategory:'Fog & Noise',description:'低周波ノイズで生成した雲状の濃淡が漂い、霧・煙のような空気感を作る。',purpose:'Immersive / Luxury / Art',tech:['CSS filter / Canvas / shader'],editable:['density','scale','drift','opacity'],difficulty:'Medium',load:'Medium',priority:'A',previewType:'background',variants:[{id:'background-noise-cloud',nameJa:'ノイズ雲・ドリフト',nameEn:'Noise Cloud Drift'}]},
{id:'object-floating-product',nameJa:'浮遊プロダクト・ターン',nameEn:'Floating Product Turn',category:'object',categoryName:'3D / Object',subcategory:'Product',description:'中央のプロダクトがゆっくり浮遊しながらY軸回転し、スペキュラー光が表面を走る。',purpose:'Product / Fashion / Automotive',tech:['Three.js / CSS 3D'],editable:['rotation','float','light','camera'],difficulty:'Hard',load:'Heavy',priority:'A',previewType:'object',variants:[{id:'object-floating-product',nameJa:'浮遊プロダクト・ターン',nameEn:'Floating Product Turn'}]},
{id:'object-exploded-assembly',nameJa:'分解アセンブリ・ビュー',nameEn:'Exploded Assembly View',category:'object',categoryName:'3D / Object',subcategory:'Exploded View',description:'構成部品が中心から分解・展開し、構造を見せた後に再度組み上がる。',purpose:'Product / Engineering / Explainer',tech:['Three.js / GSAP'],editable:['part count','distance','sequence','labels'],difficulty:'Hard',load:'Heavy',priority:'A',previewType:'object',variants:[{id:'object-exploded-assembly',nameJa:'分解アセンブリ・ビュー',nameEn:'Exploded Assembly View'}]},
{id:'navigation-radial-orbit',nameJa:'放射オービット・ナビ',nameEn:'Radial Orbit Navigation',category:'navigation',categoryName:'Navigation',subcategory:'Experimental Nav',description:'メニュー項目を円周上に配置し、選択に合わせてリング全体が回転して中央に対象を移動する。',purpose:'Portfolio / Brand / Creative menu',tech:['CSS transform / GSAP'],editable:['radius','items','snap','rotation'],difficulty:'Medium',load:'Light',priority:'A',previewType:'navigation',variants:[{id:'navigation-radial-orbit',nameJa:'放射オービット・ナビ',nameEn:'Radial Orbit Navigation'}]},
{id:'navigation-cursor-mega-menu',nameJa:'カーソル追従メガメニュー',nameEn:'Cursor-follow Mega Menu',category:'navigation',categoryName:'Navigation',subcategory:'Mega Menu',description:'ナビ項目のhoverに合わせて大型プレビュー面がカーソル方向へ遅延追従し、項目ごとに内容が切り替わる。',purpose:'Fashion / Portfolio / Editorial',tech:['Pointer Events / GSAP'],editable:['lag','preview size','offset','transition'],difficulty:'Medium',load:'Medium',priority:'A',previewType:'navigation',variants:[{id:'navigation-cursor-mega-menu',nameJa:'カーソル追従メガメニュー',nameEn:'Cursor-follow Mega Menu'}]},
{id:'loader-orbit-assembly',nameJa:'オービット・アセンブリローダー',nameEn:'Orbit Assembly Loader',category:'loader',categoryName:'Loaders',subcategory:'Orbit',description:'複数の小要素が軌道上を回りながら中央へ集まり、ロゴ形状を組み立てるローダー。',purpose:'Intro / Brand / App loading',tech:['CSS / SVG / GSAP'],editable:['particles','orbit','duration','logo'],difficulty:'Medium',load:'Light',priority:'A',previewType:'loader',variants:[{id:'loader-orbit-assembly',nameJa:'オービット・アセンブリローダー',nameEn:'Orbit Assembly Loader'}]},
{id:'loader-progress-scan',nameJa:'スキャンライン進捗ローダー',nameEn:'Scanline Progress Loader',category:'loader',categoryName:'Loaders',subcategory:'Progress',description:'走査線が画面を横断しながら進捗率を更新し、データ読み込み感を演出する。',purpose:'Tech / Game / Data',tech:['CSS / JS progress'],editable:['speed','line width','counter','glow'],difficulty:'Easy',load:'Light',priority:'A',previewType:'loader',variants:[{id:'loader-progress-scan',nameJa:'スキャンライン進捗ローダー',nameEn:'Scanline Progress Loader'}]}
];
