const IMG={a:'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80',b:'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=900&q=80',c:'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=900&q=80',d:'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80'};
const pic=(src,cls='')=>`<img class="${cls}" src="${src}" alt="sample visual">`;
export function mediaPreview(f){const id=f.id||'';
if(id==='scroll-horizontal-gallery')return `<div class="pv media-gallery"><div>${pic(IMG.a)}${pic(IMG.b)}${pic(IMG.c)}${pic(IMG.d)}</div><b>HORIZONTAL GALLERY</b></div>`;
if(id==='cursor-image-trail')return `<div class="pv media-trail">${pic(IMG.a)}${pic(IMG.b)}${pic(IMG.c)}${pic(IMG.d)}</div>`;
if(id.includes('text-image-interlock'))return `<div class="pv media-interlock"><b>TYPE</b>${pic(IMG.b)}<strong>IMAGE</strong></div>`;
if(id.includes('caption-lock'))return `<div class="pv media-caption"><div><small>01 / PRODUCT</small><b>LOCKED CAPTION</b><p>Copy stays fixed while the visual changes.</p></div>${pic(IMG.c)}</div>`;
if(id.includes('image-displacement'))return `<div class="pv media-displace">${pic(IMG.a,'base')}${pic(IMG.d,'top')}<b>DISPLACEMENT</b></div>`;
if(id.includes('zoom-pan'))return `<div class="pv media-zoompan">${pic(IMG.b)}<i></i><b>ZOOM / PAN</b></div>`;
if(id.includes('video-play'))return `<div class="pv media-video">${pic(IMG.c)}<button>▶</button><b>HOVER TO PLAY</b></div>`;
if(id.includes('slice-swap'))return `<div class="pv media-slices">${Array.from({length:6},(_,i)=>`<i style="--i:${i};background-image:url('${i%2?IMG.a:IMG.d}')"></i>`).join('')}</div>`;
if(id.includes('depth-layers'))return `<div class="pv media-depth">${pic(IMG.a,'back')}${pic(IMG.b,'mid')}${pic(IMG.c,'front')}<b>DEPTH LAYERS</b></div>`;
if(id.includes('carousel-inertia'))return `<div class="pv media-carousel">${pic(IMG.a)}${pic(IMG.b)}${pic(IMG.c)}${pic(IMG.d)}</div>`;
if(id.includes('globe-gallery'))return `<div class="pv media-globe">${[IMG.a,IMG.b,IMG.c,IMG.d,IMG.a,IMG.b].map((s,i)=>`<img style="--i:${i}" src="${s}" alt="sample visual">`).join('')}</div>`;
if(id.includes('before-after'))return `<div class="pv media-beforeafter"><div class="before">${pic(IMG.a)}</div><div class="after">${pic(IMG.d)}</div><i></i><b>BEFORE</b><strong>AFTER</strong></div>`;
if(id.includes('xray'))return `<div class="pv media-xray">${pic(IMG.b,'surface')}${pic(IMG.c,'inside')}<i></i><b>X-RAY</b></div>`;
if(id.includes('lens-magnify'))return `<div class="pv media-lens">${pic(IMG.a)}<i>${pic(IMG.a)}</i><b>MAGNIFY</b></div>`;
if(id.includes('family-media-scroll'))return `<div class="pv media-family">${pic(IMG.a)}${pic(IMG.b)}${pic(IMG.c)}<b>MEDIA SCROLL</b></div>`;
if(id==='transition-shutter-slice')return `<div class="pv exp-shutter">${Array.from({length:8},(_,i)=>`<i style="--i:${i}"></i>`).join('')}<b>SHUTTER</b></div>`;
if(id==='transition-iris-aperture')return `<div class="pv exp-iris">${pic(IMG.d)}<i></i><b>IRIS</b></div>`;
if(id==='transition-card-flip')return `<div class="pv exp-flip"><i class="front">SCENE A</i><i class="back">SCENE B</i></div>`;
if(id==='background-aurora-flow')return `<div class="pv exp-aurora"><i></i><i></i><i></i><b>AURORA</b></div>`;
if(id==='background-grid-warp')return `<div class="pv exp-grid"><i></i><b>GRID WARP</b></div>`;
if(id==='background-noise-cloud')return `<div class="pv exp-cloud"><i></i><i></i><i></i><b>NOISE CLOUD</b></div>`;
if(id==='object-floating-product')return `<div class="pv exp-product"><i>PRODUCT</i><b>FLOAT / TURN</b></div>`;
if(id==='object-exploded-assembly')return `<div class="pv exp-assembly"><i>1</i><i>2</i><i>3</i><i>4</i><b>ASSEMBLY</b></div>`;
if(id==='navigation-radial-orbit')return `<div class="pv exp-radial"><b>MENU</b>${Array.from({length:6},(_,i)=>`<i style="--i:${i}">${String(i+1).padStart(2,'0')}</i>`).join('')}</div>`;
if(id==='navigation-cursor-mega-menu')return `<div class="pv exp-mega"><div><b>WORK</b><b>ABOUT</b><b>CONTACT</b></div>${pic(IMG.b)}<i>VIEW</i></div>`;
if(id==='loader-orbit-assembly')return `<div class="pv exp-loader-orbit"><b>M</b>${Array.from({length:7},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div>`;
if(id==='loader-progress-scan')return `<div class="pv exp-loader-scan"><b>68%</b><i></i><span></span></div>`;
return null;
}
