const E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const T=(f,cls,label=f.nameEn)=>`<div class="pv sem ${cls}"><b>${E(label)}</b><span>${E(f.id)}</span></div>`;
export function semanticPreview(f){const id=f.id||'';
if(id.includes('baseline'))return T(f,'sem-baseline','BASELINE SHIFT');
if(id.includes('line-height'))return `<div class="pv sem sem-lineheight"><b>VARIABLE<br>LINE<br>HEIGHT</b></div>`;
if(id.includes('scroll-scale'))return T(f,'sem-scale','SCROLL SCALE');
if(id.includes('scroll-rotate'))return T(f,'sem-rotate','SCROLL ROTATE');
if(id.includes('sticky-stack'))return `<div class="pv sem sem-stack"><i>TYPE</i><i>TYPE</i><i>TYPE</i></div>`;
if(id.includes('mouse-repel'))return `<div class="pv sem sem-repel"><b>REPEL</b><i></i></div>`;
if(id.includes('mouse-attract'))return `<div class="pv sem sem-attract"><b>ATTRACT</b><i></i></div>`;
if(id.includes('hover-slice'))return `<div class="pv sem sem-slice"><b>SLICE</b><i></i><i></i><i></i></div>`;
if(id.includes('stroke-fill'))return T(f,'sem-strokefill','STROKE / FILL');
if(id.includes('svg-path')||id.includes('path-follow'))return `<div class="pv sem sem-path"><svg viewBox="0 0 500 220"><path id="p" d="M20 150 C120 20 240 220 480 70"/><text><textPath href="#p">PATH FOLLOWING TYPE • PATH FOLLOWING TYPE</textPath></text></svg></div>`;
if(id.includes('handwriting'))return T(f,'sem-write','HANDWRITING');
if(id.includes('neon'))return T(f,'sem-neon','NEON FLICKER');
if(id.includes('reflection'))return `<div class="pv sem sem-reflect"><b>REFLECT</b><b>REFLECT</b></div>`;
if(id.includes('chromatic'))return T(f,'sem-chroma','CHROMATIC');
if(id.includes('scanline'))return T(f,'sem-scan','SCANLINE');
if(id.includes('ascii'))return T(f,'sem-ascii','A5C11');
if(id.includes('particle-rebuild'))return `<div class="pv sem sem-particles"><b>REBUILD</b>${Array.from({length:22},()=>'<i></i>').join('')}</div>`;
if(id.includes('liquid-metal'))return T(f,'sem-metal','LIQUID METAL');
if(id.includes('refractive-glass'))return T(f,'sem-glass','GLASS TYPE');
if(id.includes('zoom-through'))return T(f,'sem-zoomthrough','ZOOM THROUGH');
if(id.includes('rotate-gallery'))return `<div class="pv sem sem-wheel"><i>01</i><i>02</i><i>03</i><i>04</i></div>`;
if(id.includes('fold-section'))return `<div class="pv sem sem-fold"><i>FRONT</i><i>BACK</i></div>`;
if(id.includes('compress-expand'))return T(f,'sem-compress','COMPRESS / EXPAND');
if(id.includes('svg-path-reveal'))return `<div class="pv sem sem-draw"><svg viewBox="0 0 500 220"><path d="M20 170 C100 20 200 210 300 60 S450 160 480 40"/></svg></div>`;
if(id.includes('video-mask'))return `<div class="pv sem sem-videomask"><b>VIDEO</b><i></i></div>`;
if(id.includes('frame-by-frame'))return `<div class="pv sem sem-frames"><b>01</b><b>02</b><b>03</b><b>04</b></div>`;
if(id.includes('before-after'))return `<div class="pv sem sem-beforeafter"><b>BEFORE</b><b>AFTER</b><i></i></div>`;
if(id.includes('timeline-marker'))return `<div class="pv sem sem-timeline"><i></i><i></i><i></i><b>2024</b></div>`;
if(id.includes('progress-ring'))return `<div class="pv sem sem-progress"><i></i><b>72%</b></div>`;
if(id.includes('snap-scenes'))return `<div class="pv sem sem-snap"><i>01</i><i>02</i><i>03</i></div>`;
if(id.includes('gradient-shift'))return T(f,'sem-gradient','GRADIENT SHIFT');
if(id.includes('fog-density'))return `<div class="pv sem sem-fog"><i></i><i></i><i></i><b>FOG</b></div>`;
if(id.includes('light-sweep'))return `<div class="pv sem sem-light"><b>LIGHT SWEEP</b><i></i></div>`;
if(id.includes('noise-transition'))return T(f,'sem-noise','NOISE EROSION');
if(id.includes('text-image-interlock'))return `<div class="pv sem sem-interlock"><b>TYPE</b><i></i><b>IMAGE</b></div>`;
if(id.includes('caption-lock'))return `<div class="pv sem sem-caption"><b>LOCKED CAPTION</b><i>MEDIA</i></div>`;
if(id.includes('editorial-columns'))return `<div class="pv sem sem-columns"><i>COL A</i><i>COL B</i><i>COL C</i></div>`;
if(id.includes('quote-scale'))return T(f,'sem-quote','“QUOTE”');
if(id.includes('map-journey'))return `<div class="pv sem sem-map"><svg viewBox="0 0 500 220"><path d="M20 180 C100 20 230 210 480 50"/></svg><b>ROUTE</b></div>`;
if(id.includes('process-build'))return `<div class="pv sem sem-build"><i>1</i><i>2</i><i>3</i><i>4</i></div>`;
if(id.includes('timeline-eras'))return `<div class="pv sem sem-eras"><b>1980</b><b>2000</b><b>2026</b></div>`;
if(id.includes('data-story'))return `<div class="pv sem sem-data"><i></i><i></i><i></i><i></i><b>DATA STORY</b></div>`;
if(id.includes('magnetic-nav'))return `<div class="pv sem sem-magnav"><b>WORK</b><b>ABOUT</b><b>CONTACT</b><i></i></div>`;
if(id.includes('custom-state'))return `<div class="pv sem sem-cursorstate"><i>VIEW</i><b>HOVER TARGET</b></div>`;
if(id.includes('dot-ring'))return `<div class="pv sem sem-dotring"><i></i><i></i></div>`;
if(id.includes('label-preview'))return `<div class="pv sem sem-label"><b>PROJECT</b><i>VIEW</i></div>`;
if(id.includes('thumbnail-follow'))return `<div class="pv sem sem-thumb"><b>PROJECT LIST</b><i>PREVIEW</i></div>`;
if(id.includes('spring-follow'))return `<div class="pv sem sem-spring"><i></i><b>SPRING</b></div>`;
if(id.includes('rope-chain'))return `<div class="pv sem sem-rope">${Array.from({length:9},()=>'<i></i>').join('')}</div>`;
if(id.includes('cloth-pull'))return `<div class="pv sem sem-cloth"><i></i><b>CLOTH</b></div>`;
if(id.includes('jelly-button'))return `<div class="pv sem sem-jelly"><button>JELLY</button></div>`;
if(id.includes('image-displacement'))return `<div class="pv sem sem-displace"><i></i><b>DISPLACE</b></div>`;
if(id.includes('zoom-pan'))return `<div class="pv sem sem-zoompan"><i></i><b>ZOOM / PAN</b></div>`;
if(id.includes('video-play'))return `<div class="pv sem sem-hovervideo"><i>▶</i><b>HOVER VIDEO</b></div>`;
if(id.includes('slice-swap'))return `<div class="pv sem sem-swapslice"><i></i><i></i><i></i><i></i></div>`;
if(id.includes('depth-layers'))return `<div class="pv sem sem-depthlayers"><i>BACK</i><i>MID</i><i>FRONT</i></div>`;
if(id.includes('carousel-inertia'))return `<div class="pv sem sem-carousel"><i>1</i><i>2</i><i>3</i><i>4</i></div>`;
if(id.includes('globe-gallery'))return `<div class="pv sem sem-globe">${Array.from({length:8},(_,i)=>`<i style="--i:${i}">${i+1}</i>`).join('')}</div>`;
if(id.includes('elastic-sheet'))return `<div class="pv sem sem-elastic"><i></i><b>DRAG</b></div>`;
if(id.includes('radial-menu'))return `<div class="pv sem sem-radial"><b>+</b>${Array.from({length:6},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div>`;
if(id.includes('burst-particles'))return `<div class="pv sem sem-burst">${Array.from({length:18},(_,i)=>`<i style="--i:${i}"></i>`).join('')}</div>`;
if(id.includes('hold-charge'))return `<div class="pv sem sem-charge"><button>HOLD</button><i></i></div>`;
if(id.includes('page-ripple'))return `<div class="pv sem sem-pageripple"><i></i><b>CLICK</b></div>`;
if(id.includes('gooey-nav'))return `<div class="pv sem sem-gooey"><b>ONE</b><b>TWO</b><i></i></div>`;
if(id.includes('turbulence'))return T(f,'sem-turbulence','TURBULENCE');
if(id.includes('liquid-border'))return `<div class="pv sem sem-liquidborder"><button>LIQUID BORDER</button></div>`;
if(id.includes('gradient-follow'))return `<div class="pv sem sem-followgrad"><i></i><b>FOLLOW</b></div>`;
if(id.includes('specular'))return `<div class="pv sem sem-specular"><i></i><b>SPECULAR</b></div>`;
if(id.includes('iridescent'))return T(f,'sem-iridescent','IRIDESCENT');
if(id.includes('pixelate'))return T(f,'sem-pixelate','PIXELATE');
if(id.includes('dither'))return T(f,'sem-dither','DITHER');
if(id.includes('family-variable-font'))return T(f,'sem-variablefamily','VARIABLE FONT');
if(id.includes('family-kinetic-type'))return T(f,'sem-kineticfamily','KINETIC TYPE');
if(id.includes('family-3d-type'))return T(f,'sem-3dtype','3D TYPE');
if(id.includes('family-shader-type'))return T(f,'sem-shader','SHADER TYPE');
if(id.includes('family-editorial-type'))return T(f,'sem-editorial','EDITORIAL TYPE');
if(id.includes('family-scroll-type'))return T(f,'sem-scrolltype','SCROLL TYPE');
if(id.includes('family-camera-scroll'))return `<div class="pv sem sem-camerafamily"><i></i><i></i><b>CAMERA SCROLL</b></div>`;
if(id.includes('family-sticky-story'))return `<div class="pv sem sem-stickyfamily"><i>01</i><i>02</i><i>03</i><b>STICKY STORY</b></div>`;
if(id.includes('family-depth-scroll'))return `<div class="pv sem sem-depthfamily"><i></i><i></i><i></i><b>DEPTH SCROLL</b></div>`;
if(id.includes('family-material-scroll'))return T(f,'sem-material','MATERIAL SCROLL');
if(id.includes('family-particle-scroll'))return `<div class="pv sem sem-particlefamily">${Array.from({length:16},()=>'<i></i>').join('')}<b>PARTICLE SCROLL</b></div>`;
if(id.includes('family-media-scroll'))return `<div class="pv sem sem-mediafamily"><i>MEDIA</i><i>MEDIA</i><i>MEDIA</i></div>`;
if(id.includes('family-magnetic'))return `<div class="pv sem sem-magneticfamily"><button>MAGNETIC</button><i></i></div>`;
if(id.includes('family-velocity'))return T(f,'sem-velocityfamily','VELOCITY');
if(id.includes('family-refraction'))return T(f,'sem-refractionfamily','REFRACTION');
if(id.includes('family-drag'))return `<div class="pv sem sem-dragfamily"><i>DRAG</i><i>DRAG</i><i>DRAG</i></div>`;
if(id.includes('family-proximity'))return `<div class="pv sem sem-proximity"><b>PROXIMITY</b><i></i></div>`;
return null;
}
